version: '3'

services:
  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
  backend:
    image: django-dev:latest
    build:
      context: .
    volumes:
      - .:/app:z
    entrypoint: pipenv run
    command: python project/manage.py runserver 0.0.0.0:8000
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/project
